# Generated by Django 6.0.4 on 2026-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
